In [36]:
import collections
import pandas as pd

In [37]:
success_fraction = collections.defaultdict(list)
speedup_learn = collections.defaultdict(list)
speedup_opt = collections.defaultdict(list)
for search_space in range(20, 101, 10):
    for budget in range(100, 1001, 100):
        path = f"../simulation_5e-3/n_{search_space:03d}_budget_{budget:04d}_00.csv"
        df = pd.read_csv(path, index_col=0).transpose()
        assert len(df.columns) == 4
        assert df.columns[0] == "Default"
        assert df["Default"].min() == df["Default"].max() == 1.0
        assert df.columns[1] == "Train"
        assert df.columns[3] == "Optimal"
        try:
            assert repetitions == len(df.index)
        except NameError:
            repetitions = len(df.index)
        tuner = df.columns[2]
        success_count = (df[tuner] < df["Train"]).sum()
        success_fraction[search_space].append(success_count / repetitions)
        speedup_learn[search_space].append((df["Train"] / df[tuner]).mean())
        speedup_opt[search_space].append((df[tuner] / df["Optimal"]).mean())

In [38]:
repetitions

16

In [39]:
# Probability that the learned flags are better than the best flags from the training data
pd.DataFrame(success_fraction, index=range(100, 1001, 100))

         20      30      40      50      60      70      80      90      100
100   0.6875  0.7500  0.8125  0.6875  0.8125  0.8750  0.7500  0.7500  0.8125
200   1.0000  0.8750  0.8125  0.8125  0.8125  0.8125  1.0000  0.8750  0.8750
300   1.0000  0.9375  0.9375  0.8750  0.9375  1.0000  0.9375  0.9375  1.0000
400   1.0000  0.9375  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
500   0.8750  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
600   0.9375  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
700   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
800   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
900   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
1000  0.9375  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000

In [40]:
# Speedup of the learned flags over the best flags from the training data
pd.DataFrame(speedup_learn, index=range(100, 1001, 100))

,20,30,40,50,60,70,80,90,100
100,1.022293,1.027904,1.032878,1.013069,1.012908,1.042208,1.006078,1.023068,1.014099
200,1.046254,1.046633,1.054202,1.041562,1.067736,1.064338,1.054650,1.048006,1.065959
300,1.070054,1.076841,1.068715,1.059705,1.099599,1.113164,1.094042,1.099713,1.117914
400,1.075888,1.100628,1.111595,1.117955,1.113109,1.144561,1.105927,1.112309,1.153975
500,1.068285,1.105679,1.124674,1.143662,1.154445,1.188984,1.136312,1.161793,1.177137
600,1.065800,1.104221,1.122657,1.153389,1.169747,1.206899,1.152645,1.171894,1.179353
700,1.064808,1.103496,1.124093,1.156174,1.170934,1.221522,1.168095,1.174491,1.206300
800,1.062927,1.099910,1.121031,1.158563,1.175148,1.224605,1.171592,1.182664,1.214121
900,1.062257,1.101679,1.122499,1.157099,1.172877,1.223148,1.167694,1.180798,1.209437
1000,1.058500,1.095608,1.116147,1.157392,1.173684,1.221905,1.166450,1.181716,1.205439

In [41]:
# Speedup of the optimal flags over the learned flags
pd.DataFrame(speedup_opt, index=range(100, 1001, 100))

,20,30,40,50,60,70,80,90,100
100,1.082035,1.129224,1.140571,1.201200,1.220493,1.228014,1.218347,1.216728,1.252898
200,1.043034,1.095274,1.110927,1.146562,1.133379,1.181729,1.142473,1.170406,1.181117
300,1.017805,1.054798,1.089877,1.115177,1.093989,1.121854,1.099728,1.101175,1.116965
400,1.010869,1.023331,1.038694,1.054048,1.075260,1.089046,1.086729,1.085824,1.075314
500,1.009141,1.010094,1.013135,1.027386,1.032935,1.042586,1.047582,1.035316,1.045968
600,1.006341,1.005530,1.009208,1.017116,1.018162,1.024778,1.028761,1.021282,1.041625
700,1.005504,1.006167,1.004515,1.012365,1.014081,1.009764,1.013419,1.017666,1.014588
800,1.005049,1.005466,1.006744,1.006769,1.008481,1.004848,1.009258,1.010388,1.006814
900,1.004548,1.003708,1.005335,1.005943,1.010090,1.003940,1.006506,1.010956,1.006431
1000,1.008180,1.004745,1.006082,1.005154,1.009085,1.004945,1.005380,1.008024,1.004876